### ISSUE TITLE
no attribute named dampening

### ISSUE THREAD

**Issue by beegica** [Tony-Y/pytorch_warmup#7]
I tried to run your emnist example and got this error: 
Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 152, in main
    warmup_scheduler, epoch, history)
  File "main.py", line 42, in train
    with warmup_scheduler.dampening():
AttributeError: 'UntunedLinearWarmup' object has no attribute 'dampening'

I can't seem to get any of your warmups to work. Do you have any idea why that might be? 

Thanks so much!

**Comment by Tony-Y** [comment]
You probably use an older version. Please upgrade `pytorch_warmup` as the following:
```
pip install -U pytorch_warmup
```
